local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ss', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>ws', function()
	builtin.grep_string()
end)
vim.keymap.set('n', '<leader>ps', function()
	builtin.live_grep()
end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
